/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import dao.TblCategoryDAO;
import dao.TblProductDAO;
import dto.Category;
import dto.Product;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author By Van Lung, IDStudent: SE140193
 */
public class ManagementGUI extends javax.swing.JFrame {

    TblProductDAO modelProduct;
    TblCategoryDAO modelCategory;
    final int SUCCESS = 1;
    boolean addNewPro = true;
    boolean addNewCa = true;
    boolean deleteCa = true;
    boolean deletePro = true;

    public ManagementGUI() throws Exception {
        initComponents();

        modelCategory = new TblCategoryDAO();
        tblCate.setModel(modelCategory.getModelCa());

        modelProduct = new TblProductDAO();
        tblProduct.setModel(modelProduct.getModelItem());

        try {
            cbCaName.setModel(new DefaultComboBoxModel<>(modelCategory.getListCategoryComboBox()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void clearInformationProductOnTable() {
        txtProID.setText("");
        txtProName.setText("");
        cbCaName.setSelectedItem(null);
        txtUnit.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
    }

    void clearInformationCateOnTable() {
        txtCaCode.setText("");
        txtCaName.setText("");
        txtDes.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCate = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCate = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txtCaCode = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        txtCaName = new javax.swing.JTextField();
        btnCateNew = new javax.swing.JButton();
        btnCateSave = new javax.swing.JButton();
        btnCateDelete = new javax.swing.JButton();
        PanelProduct = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        txtProID = new javax.swing.JTextField();
        txtProName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnProNew = new javax.swing.JButton();
        btnProSave = new javax.swing.JButton();
        btnProDelete = new javax.swing.JButton();
        cbCaName = new javax.swing.JComboBox<>();
        label10 = new java.awt.Label();
        txtUnit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(153, 153, 153))); // NOI18N

        tblCate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblCate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category ID", "Category Name", "Description"
            }
        ));
        tblCate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCate);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 51, 255));
        jPanel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Category ID:");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Category Name:");

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("Description:");

        btnCateNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCateNew.setText("ADD NEW");
        btnCateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateNewActionPerformed(evt);
            }
        });

        btnCateSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCateSave.setText("SAVE");
        btnCateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateSaveActionPerformed(evt);
            }
        });

        btnCateDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCateDelete.setText("DELETE");
        btnCateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCateNew)
                        .addGap(93, 93, 93)
                        .addComponent(btnCateSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 103, Short.MAX_VALUE)
                        .addComponent(btnCateDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCaName, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCaCode)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCaName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDes)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCateDelete)
                    .addComponent(btnCateSave)
                    .addComponent(btnCateNew))
                .addGap(83, 83, 83))
        );

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout PanelCateLayout = new javax.swing.GroupLayout(PanelCate);
        PanelCate.setLayout(PanelCateLayout);
        PanelCateLayout.setHorizontalGroup(
            PanelCateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelCateLayout.setVerticalGroup(
            PanelCateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("Category", PanelCate);

        PanelProduct.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main path:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(153, 153, 153))); // NOI18N

        tblProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Unit", "Quantity", "Price", "Category ID"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        PanelProduct.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details path:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(153, 153, 153))); // NOI18N

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("Product Name:");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Product ID:");

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("Category Name:");

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setText("Quantity:");

        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setText("Price:");

        txtProID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProIDActionPerformed(evt);
            }
        });

        txtProName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnProNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProNew.setText("Add New");
        btnProNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProNewActionPerformed(evt);
            }
        });

        btnProSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProSave.setText("Save");
        btnProSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProSaveActionPerformed(evt);
            }
        });

        btnProDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProDelete.setText("Delete");
        btnProDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProDeleteActionPerformed(evt);
            }
        });

        cbCaName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbCaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCaNameMouseClicked(evt);
            }
        });
        cbCaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaNameActionPerformed(evt);
            }
        });

        label10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label10.setText("Unit:");

        txtUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProNew, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnProSave, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnProDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUnit)
                    .addComponent(txtPrice)
                    .addComponent(txtQuantity)
                    .addComponent(cbCaName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProName)
                    .addComponent(txtProID)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCaName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProNew, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        PanelProduct.add(jPanel7);

        jTabbedPane1.addTab("Product", PanelProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCateMouseClicked
        int selectedRow = tblCate.getSelectedRow();
        Category ca = modelCategory.getModelCa().getList().get(selectedRow);
        txtCaCode.setText(ca.getCategoryID());
        txtCaCode.setEditable(false);
        txtCaName.setText(ca.getCategoryName());
        txtDes.setText(ca.getDescription());
        addNewCa = false;
        deleteCa = false;
    }//GEN-LAST:event_tblCateMouseClicked

    private void btnCateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateNewActionPerformed
        txtCaCode.setEditable(true);
        clearInformationCateOnTable();
        addNewCa = true;
        deleteCa = false;
    }//GEN-LAST:event_btnCateNewActionPerformed

    private void btnCateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateSaveActionPerformed
        if (!modelCategory.validDate(txtCaCode.getText().trim(), txtCaName.getText().trim(), txtDes.getText().trim())) {
            return;

        }
        if (addNewCa) {
            try {
                if (!modelCategory.validDateCodeCategory(txtCaCode.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "DUPLICATE CATEGORY ID AT " + txtCaCode.getText().trim());
                    return;
                }
                Category ca = new Category(txtCaCode.getText().trim(), txtCaName.getText().trim(), txtDes.getText().trim());
                if (modelCategory.Insert(ca) == SUCCESS) {
                    modelCategory.getModelCa().getList().add(ca);
                    modelCategory.getListCategoryComboBox().add(ca.getCategoryID() + " - " + ca.getCategoryName());
                }
                addNewCa = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblCate.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Choose Row To Edit!!");
                    return;
                }
                Category caNew = new Category(txtCaCode.getText().trim(), txtCaName.getText().trim(), txtDes.getText().trim());
                Category ca01d = modelCategory.getModelCa().getList().get(selectedRow);
                if (modelCategory.Save(caNew) == SUCCESS) {
                    modelCategory.getListCategoryComboBox().remove(ca01d.getCategoryID() + " - " + ca01d.getCategoryName());
                    ca01d.setCategoryName(caNew.getCategoryName());
                    ca01d.setDescription(caNew.getDescription());

                    modelCategory.getListCategoryComboBox().add(caNew.getCategoryID() + " - " + caNew.getCategoryName());
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        modelProduct.getModelItem().loadCateprogyComboBox();
        cbCaName.setModel(new DefaultComboBoxModel<>(modelCategory.getListCategoryComboBox()));
        tblCate.updateUI();

    }//GEN-LAST:event_btnCateSaveActionPerformed

    private void btnCateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateDeleteActionPerformed
        try {
            int selectedRow = tblCate.getSelectedRow();
            if (selectedRow < 0 || deleteCa == false) {
                JOptionPane.showMessageDialog(this, "This category was used.You cannot delete Category "
                        + "");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to delete this Category?");
            if (r == JOptionPane.YES_OPTION) {
                Category ca = modelCategory.getModelCa().getList().get(selectedRow);
                if (!modelProduct.checkconstraintCaCode(ca.getCategoryID())) {
                    JOptionPane.showMessageDialog(this, "Still items is manager by this Category");
                    return;
                }
                if (modelCategory.Delete(ca) == SUCCESS) {
                    deleteCa = false;
                    modelCategory.getModelCa().getList().remove(ca);
                    modelCategory.getListCategoryComboBox().remove(ca.getCategoryID() + "-" + ca.getCategoryName());
                    JOptionPane.showMessageDialog(this, "Deleted!");
                    cbCaName.setModel(new DefaultComboBoxModel<>(modelCategory.getListCategoryComboBox()));
                    clearInformationCateOnTable();
                    modelProduct.getModelItem().loadCateprogyComboBox();
                    tblCate.updateUI();

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCateDeleteActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        int selectedRow = tblProduct.getSelectedRow();

        try {
            if (selectedRow >= 0) {
                Product it = modelProduct.getModelItem().getList().get(selectedRow);
                txtProID.setText(it.getProductID());
                txtProID.setEditable(false);
                txtProName.setText(it.getProductName());
                txtUnit.setText(it.getUnit());
                txtQuantity.setText(it.getQuantity() + "");
                txtPrice.setText(it.getPrice() + "");

                cbCaName.setSelectedItem(it.getCategoryID() + " - " + modelCategory.getCaNameComboBox(it.getCategoryID()));
//                cbCaName.setSelectedItem(getName((String) tblProduct.getValueAt(selectedRow, NORMAL)));
                addNewPro = false;
                deletePro = true;
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_tblProductMouseClicked

    private void txtProIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProIDActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnProNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProNewActionPerformed
        txtProID.setEditable(true);
        clearInformationProductOnTable();
        addNewPro = true;
        deletePro = false;
    }//GEN-LAST:event_btnProNewActionPerformed

    private void btnProSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProSaveActionPerformed
//        if (!modelProduct.validDate(txtProID.getText().trim(), txtProName.getText().trim(), txtUnit.getText().trim(), txtQuantity.getText().trim(), txtPrice.getText().trim(), cbCaName.getSelectedItem())) {
//            return;
//        }
//        if (addNewPro) {
//            try {
//                if (!modelProduct.validDateCodeProduct(txtProID.getText().trim())) {
//                    JOptionPane.showMessageDialog(this, "DUPLICATED ITEMCODE at " + txtProID.getText().trim());
//                    return;
//                }
//                Product proNew = new Product(txtProID.getText().toUpperCase().trim(), txtProName.getText().trim(), txtUnit.getText().trim(), txtQuantity.getText().trim(),
//                        Float.parseFloat(txtPrice.getText().trim()), modelProduct.loadCaCodeIntoItems(cbCaName.getSelectedItem().toString()));
//                if (modelProduct.Insert(proNew) == SUCCESS) {
//                    modelProduct.getModelItem().getList().add(proNew);
//                }
//                addNewPro = false;
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        } else {
//            try {
//                int selectedRow = tblProduct.getSelectedRow();
//                if (selectedRow < 0) {
//                    JOptionPane.showMessageDialog(this, "Please Choose Row to Edit");
//                }
//                Product pro01d = modelProduct.getModelItem().getList().get(selectedRow);
//                Product proNew = new Product(txtProID.getText().toUpperCase().trim(), txtProName.getText().trim(), txtUnit.getText().trim(), txtQuantity.getText().trim(),
//                        Float.parseFloat(txtPrice.getText().trim()), modelProduct.loadCaCodeIntoItems(cbCaName.getSelectedItem().toString()));
//                if (modelProduct.Save(proNew) == SUCCESS) {
//                    pro01d.setProductName(proNew.getProductName());
//                    pro01d.setUnit(proNew.getUnit());
//                    pro01d.setQuantity(proNew.getQuantity());
//                    pro01d.setPrice(proNew.getPrice());
//                    pro01d.setCategoryID(proNew.getCategoryID());
//                }
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
//        tblProduct.updateUI();
    }//GEN-LAST:event_btnProSaveActionPerformed

    private void btnProDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProDeleteActionPerformed
        try {
            int selectedRow = tblProduct.getSelectedRow();
            if (selectedRow < 0 || deletePro == false) {
                JOptionPane.showMessageDialog(this, "Choose the Row to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Product?");
            if (r == JOptionPane.YES_OPTION) {
                Product it = modelProduct.getModelItem().getList().get(selectedRow);
                if (modelProduct.Delete(it) == SUCCESS) {
                    deletePro = false;
                    modelProduct.getModelItem().getList().remove(it);
                    JOptionPane.showMessageDialog(this, "Deleted");
                    clearInformationProductOnTable();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblProduct.updateUI();
    }//GEN-LAST:event_btnProDeleteActionPerformed

    private void cbCaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaNameActionPerformed

    }//GEN-LAST:event_cbCaNameActionPerformed

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void cbCaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCaNameMouseClicked

    }//GEN-LAST:event_cbCaNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManagementGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ManagementGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCate;
    private javax.swing.JPanel PanelProduct;
    private javax.swing.JButton btnCateDelete;
    private javax.swing.JButton btnCateNew;
    private javax.swing.JButton btnCateSave;
    private javax.swing.JButton btnProDelete;
    private javax.swing.JButton btnProNew;
    private javax.swing.JButton btnProSave;
    private javax.swing.JComboBox<String> cbCaName;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTable tblCate;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtCaCode;
    private javax.swing.JTextField txtCaName;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProID;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
